apiVersion: v1
kind: Template
labels:
  template: jenkins-master-builder
metadata:
  annotations:
    description: Provide a convenient way to create an image to a Jenkins master image (with jdk)
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: jenkins-master-builder
- description: Git source URI for Jenkins S2I
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/siamaksade/jenkins-s2i-example.git
- description: Git branch/tag reference
  name: SOURCE_REPOSITORY_REF
  value: master
- description: Path within Git project to build; empty for root project directory.
  name: CONTEXT_DIR
  value: master
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  value: 1Gi
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: jenkins-master
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
    name: jenkins-temp-master
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-temp-master:latest
    resources: {}
    source:
      contextDir: '1'
      git:
        ref: master
        uri: https://github.com/openshift/jenkins.git
      type: Git
    strategy:
      dockerStrategy:
      type: Docker
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: jenkins-master
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-master:latest
    resources:
      limits:
        memory: ${MEMORY_LIMIT}
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      secrets: []
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jenkins-temp-master
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: Service
  metadata:
    name: jenkins
  spec:
    ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: jnlp
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
      name: jenkins-master
      deploymentconfig: jenkins-master
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: jenkins-master
  spec:
    replicas: 1
    selector:
      name: jenkins-master
      deploymentconfig: jenkins-master
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: jenkins-master
          deploymentconfig: jenkins-master
      spec:
        containers:
        - env:
          - name: JENKINS_PASSWORD
            value: password
          image: jenkins-master
          imagePullPolicy: Always
          name: jenkins-master
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 50000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/jenkins
            name: jenkins-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: jenkins-data
          emptyDir:
            medium: ""
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - jenkins-master
        from:
          kind: ImageStreamTag
          name: jenkins-master:latest
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    name: jenkins
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: jenkins
