apiVersion: v1
kind: Template
labels:
  template: jenkins-master-builder
metadata:
  annotations:
    description: Provide a convenient way to create an image to a Jenkins master image (with jdk)
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: jenkins-master-builder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      role: jenkins-master
    name: jenkins-master
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      name: jenkins-master
    name: jenkins-master
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-master:latest
    resources: {}
    source:
      contextDir: '1'
      git:
        ref: master
        uri: https://github.com/openshift/jenkins.git
      type: Git
    strategy:
      dockerStrategy:
      type: Docker
    triggers:
    - type: ConfigChange
